# Generated by Django 4.0.7 on 2024-08-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('docente_encargado', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='proyectos')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado')], default='Pendiente', max_length=20)),
            ],
        ),
    ]
