# Generated by Django 4.0.7 on 2024-08-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_convenio', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='convenios')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
    ]
