# Generated by Django 4.0.7 on 2024-08-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avance', '0002_convenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('revista', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('impacto_factor', models.FloatField()),
                ('metrica_q', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('documento', models.FileField(blank=True, null=True, upload_to='articulos')),
                ('link_articulo', models.URLField()),
            ],
        ),
    ]
